import type { LevelDefinition } from '../types';
import { vec } from '../math';

export const levelOne: LevelDefinition = {
  id: 'blacksite-threshold',
  name: 'Blacksite Threshold',
  chapter: 'Operation Glass Dagger',
  bounds: {
    min: vec(-42, -34),
    max: vec(42, 38),
  },
  start: vec(0, -29),
  extraction: vec(0, 33),
  walls: [
    { id: 'outer-north', center: vec(0, 37.5), size: vec(84, 1), height: 3.4 },
    { id: 'outer-south', center: vec(0, -33.5), size: vec(84, 1), height: 3.4 },
    { id: 'outer-west', center: vec(-41.5, 2), size: vec(1, 70), height: 3.4 },
    { id: 'outer-east', center: vec(41.5, 2), size: vec(1, 70), height: 3.4 },
    { id: 'lobby-divider-west', center: vec(-24.5, -18), size: vec(33, 1), height: 3.2 },
    { id: 'lobby-divider-east', center: vec(24.5, -18), size: vec(33, 1), height: 3.2 },
    { id: 'server-divider-west', center: vec(-21.5, 5), size: vec(39, 1), height: 3.2 },
    { id: 'server-divider-east', center: vec(25, 5), size: vec(10, 1), height: 3.2 },
    { id: 'command-divider-west', center: vec(-24.5, 20), size: vec(33, 1), height: 3.2 },
    { id: 'command-divider-east', center: vec(24.5, 20), size: vec(33, 1), height: 3.2 },
    { id: 'armory-rail', center: vec(-13, 14), size: vec(1, 8), height: 2.4 },
    { id: 'server-rail', center: vec(13, 12), size: vec(1, 10), height: 2.4 },
  ],
  blockers: [
    { id: 'cargo-stack-a', center: vec(-27, -25), size: vec(5, 4), height: 1.35 },
    { id: 'cargo-stack-b', center: vec(27, -25), size: vec(5, 4), height: 1.35 },
    { id: 'antenna-bank', center: vec(-26, -4), size: vec(6, 3), height: 1.75 },
    { id: 'server-bank-a', center: vec(25, 11), size: vec(5, 8), height: 1.9 },
    { id: 'server-bank-b', center: vec(-25, 12), size: vec(5, 8), height: 1.9 },
    { id: 'briefing-table', center: vec(0, 26), size: vec(11, 3), height: 1.0 },
  ],
  doors: [
    {
      id: 'lobby-door',
      center: vec(0, -18),
      size: vec(6, 0.8),
      height: 3.3,
      axis: 'x',
      opensWhen: ['access-keycard'],
      speed: 1.8,
    },
    {
      id: 'server-door',
      center: vec(14, 5),
      size: vec(6, 0.8),
      height: 3.3,
      axis: 'x',
      opensWhen: ['security-terminal'],
      speed: 1.8,
    },
    {
      id: 'extraction-door',
      center: vec(0, 20),
      size: vec(6, 0.8),
      height: 3.3,
      axis: 'x',
      opensWhen: ['command-codes'],
      speed: 1.9,
    },
  ],
  objectives: [
    {
      id: 'access-keycard',
      type: 'keycard',
      label: 'Recover the lobby keycard',
      position: vec(-31, -25),
      radius: 1.55,
      required: true,
      unlocks: ['lobby-door'],
      asset: 'keycard',
    },
    {
      id: 'security-terminal',
      type: 'terminal',
      label: 'Hack the security terminal',
      position: vec(30, -3),
      radius: 1.75,
      required: true,
      unlocks: ['server-door'],
      asset: 'terminal',
    },
    {
      id: 'command-codes',
      type: 'codes',
      label: 'Copy the command codes',
      position: vec(-32, 14),
      radius: 1.55,
      required: true,
      unlocks: ['extraction-door'],
      asset: 'keycard',
    },
  ],
  enemies: [
    {
      id: 'sentry-lobby',
      label: 'Lobby sentry',
      start: vec(16, -25),
      patrol: [vec(16, -25), vec(-8, -23), vec(10, -13)],
      speed: 2.1,
      detectionRadius: 2.45,
    },
    {
      id: 'sentry-server',
      label: 'Server sentry',
      start: vec(18, 12),
      patrol: [vec(18, 12), vec(31, 15), vec(18, 1)],
      speed: 1.9,
      detectionRadius: 2.4,
    },
    {
      id: 'sentry-command',
      label: 'Command sentry',
      start: vec(-14, 25),
      patrol: [vec(-14, 25), vec(12, 25), vec(-3, 32)],
      speed: 2.0,
      detectionRadius: 2.35,
    },
  ],
  validationRoute: [
    vec(0, -29),
    vec(-31, -25),
    vec(0, -19),
    vec(1, -16),
    vec(30, -3),
    vec(15, 4),
    vec(16, 7),
    vec(-32, 14),
    vec(0, 19),
    vec(0, 24),
    vec(0, 33),
  ],
  tutorial: [
    {
      id: 'hero',
      title: 'Insertion',
      target: 'hero',
      text: 'Cadet, this is your first Shadow Recruit field operation. Move quietly, keep your suit low, and read the room before you cross open ground.',
    },
    {
      id: 'keycard',
      title: 'First Lock',
      target: 'access-keycard',
      text: 'Your first objective is the lobby keycard. Secure it to open the first sliding security door.',
    },
    {
      id: 'terminal',
      title: 'Security Stack',
      target: 'security-terminal',
      text: 'The terminal controls the server-wing door. Get close, interact, and let the deck burn through the lock.',
    },
    {
      id: 'sentry',
      title: 'Avoid Contact',
      target: 'sentry-lobby',
      text: 'Avoid sentries. If one closes in, you are done. Use cover, watch patrol timing, and do not sprint into a sightline.',
    },
    {
      id: 'extraction',
      title: 'Extraction',
      target: 'extraction',
      text: 'When the command codes unlock the final door, move to the extraction pad and hold the zone. Good luck, cadet.',
    },
  ],
};

export const levels = [levelOne] as const;
